

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("koin-compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/annotations")
  @TestDataPath("$PROJECT_ROOT")
  public class Annotations {
    @Test
    public void testAllFilesPresentInAnnotations() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/annotations"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("factory_class.kt")
    public void testFactory_class() {
      runTest("koin-compiler-plugin/testData/box/annotations/factory_class.kt");
    }

    @Test
    @TestMetadata("singleton_class.kt")
    public void testSingleton_class() {
      runTest("koin-compiler-plugin/testData/box/annotations/singleton_class.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/bindings")
  @TestDataPath("$PROJECT_ROOT")
  public class Bindings {
    @Test
    public void testAllFilesPresentInBindings() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/bindings"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("auto_interface_binding.kt")
    public void testAuto_interface_binding() {
      runTest("koin-compiler-plugin/testData/box/bindings/auto_interface_binding.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/dsl")
  @TestDataPath("$PROJECT_ROOT")
  public class Dsl {
    @Test
    public void testAllFilesPresentInDsl() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/dsl"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("create_constructor.kt")
    public void testCreate_constructor() {
      runTest("koin-compiler-plugin/testData/box/dsl/create_constructor.kt");
    }

    @Test
    @TestMetadata("factory_basic.kt")
    public void testFactory_basic() {
      runTest("koin-compiler-plugin/testData/box/dsl/factory_basic.kt");
    }

    @Test
    @TestMetadata("scoped_basic.kt")
    public void testScoped_basic() {
      runTest("koin-compiler-plugin/testData/box/dsl/scoped_basic.kt");
    }

    @Test
    @TestMetadata("single_basic.kt")
    public void testSingle_basic() {
      runTest("koin-compiler-plugin/testData/box/dsl/single_basic.kt");
    }

    @Test
    @TestMetadata("single_with_default_value.kt")
    public void testSingle_with_default_value() {
      runTest("koin-compiler-plugin/testData/box/dsl/single_with_default_value.kt");
    }

    @Test
    @TestMetadata("single_with_dependency.kt")
    public void testSingle_with_dependency() {
      runTest("koin-compiler-plugin/testData/box/dsl/single_with_dependency.kt");
    }

    @Test
    @TestMetadata("single_with_lazy.kt")
    public void testSingle_with_lazy() {
      runTest("koin-compiler-plugin/testData/box/dsl/single_with_lazy.kt");
    }

    @Test
    @TestMetadata("single_with_nullable.kt")
    public void testSingle_with_nullable() {
      runTest("koin-compiler-plugin/testData/box/dsl/single_with_nullable.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/modules")
  @TestDataPath("$PROJECT_ROOT")
  public class Modules {
    @Test
    public void testAllFilesPresentInModules() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/modules"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("component_scan_basic.kt")
    public void testComponent_scan_basic() {
      runTest("koin-compiler-plugin/testData/box/modules/component_scan_basic.kt");
    }

    @Test
    @TestMetadata("module_extension.kt")
    public void testModule_extension() {
      runTest("koin-compiler-plugin/testData/box/modules/module_extension.kt");
    }

    @Test
    @TestMetadata("module_with_functions.kt")
    public void testModule_with_functions() {
      runTest("koin-compiler-plugin/testData/box/modules/module_with_functions.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/monitor")
  @TestDataPath("$PROJECT_ROOT")
  public class Monitor {
    @Test
    public void testAllFilesPresentInMonitor() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/monitor"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("monitor_class.kt")
    public void testMonitor_class() {
      runTest("koin-compiler-plugin/testData/box/monitor/monitor_class.kt");
    }

    @Test
    @TestMetadata("monitor_function.kt")
    public void testMonitor_function() {
      runTest("koin-compiler-plugin/testData/box/monitor/monitor_function.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/params")
  @TestDataPath("$PROJECT_ROOT")
  public class Params {
    @Test
    public void testAllFilesPresentInParams() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/params"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("injected_param.kt")
    public void testInjected_param() {
      runTest("koin-compiler-plugin/testData/box/params/injected_param.kt");
    }

    @Test
    @TestMetadata("lazy_injection.kt")
    public void testLazy_injection() {
      runTest("koin-compiler-plugin/testData/box/params/lazy_injection.kt");
    }

    @Test
    @TestMetadata("property_basic.kt")
    public void testProperty_basic() {
      runTest("koin-compiler-plugin/testData/box/params/property_basic.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/qualifiers")
  @TestDataPath("$PROJECT_ROOT")
  public class Qualifiers {
    @Test
    public void testAllFilesPresentInQualifiers() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/qualifiers"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("named_on_class.kt")
    public void testNamed_on_class() {
      runTest("koin-compiler-plugin/testData/box/qualifiers/named_on_class.kt");
    }

    @Test
    @TestMetadata("named_on_parameter.kt")
    public void testNamed_on_parameter() {
      runTest("koin-compiler-plugin/testData/box/qualifiers/named_on_parameter.kt");
    }

    @Test
    @TestMetadata("qualifier_type.kt")
    public void testQualifier_type() {
      runTest("koin-compiler-plugin/testData/box/qualifiers/qualifier_type.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/safety")
  @TestDataPath("$PROJECT_ROOT")
  public class Safety {
    @Test
    public void testAllFilesPresentInSafety() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/safety"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("complete_graph.kt")
    public void testComplete_graph() {
      runTest("koin-compiler-plugin/testData/box/safety/complete_graph.kt");
    }

    @Test
    @TestMetadata("configuration_group.kt")
    public void testConfiguration_group() {
      runTest("koin-compiler-plugin/testData/box/safety/configuration_group.kt");
    }

    @Test
    @TestMetadata("default_value_ok.kt")
    public void testDefault_value_ok() {
      runTest("koin-compiler-plugin/testData/box/safety/default_value_ok.kt");
    }

    @Test
    @TestMetadata("dsl_create_function.kt")
    public void testDsl_create_function() {
      runTest("koin-compiler-plugin/testData/box/safety/dsl_create_function.kt");
    }

    @Test
    @TestMetadata("dsl_module_includes.kt")
    public void testDsl_module_includes() {
      runTest("koin-compiler-plugin/testData/box/safety/dsl_module_includes.kt");
    }

    @Test
    @TestMetadata("dsl_transitive_includes.kt")
    public void testDsl_transitive_includes() {
      runTest("koin-compiler-plugin/testData/box/safety/dsl_transitive_includes.kt");
    }

    @Test
    @TestMetadata("injected_param_ok.kt")
    public void testInjected_param_ok() {
      runTest("koin-compiler-plugin/testData/box/safety/injected_param_ok.kt");
    }

    @Test
    @TestMetadata("lazy_valid.kt")
    public void testLazy_valid() {
      runTest("koin-compiler-plugin/testData/box/safety/lazy_valid.kt");
    }

    @Test
    @TestMetadata("list_ok.kt")
    public void testList_ok() {
      runTest("koin-compiler-plugin/testData/box/safety/list_ok.kt");
    }

    @Test
    @TestMetadata("module_includes_chain.kt")
    public void testModule_includes_chain() {
      runTest("koin-compiler-plugin/testData/box/safety/module_includes_chain.kt");
    }

    @Test
    @TestMetadata("module_includes_visible.kt")
    public void testModule_includes_visible() {
      runTest("koin-compiler-plugin/testData/box/safety/module_includes_visible.kt");
    }

    @Test
    @TestMetadata("nullable_ok.kt")
    public void testNullable_ok() {
      runTest("koin-compiler-plugin/testData/box/safety/nullable_ok.kt");
    }

    @Test
    @TestMetadata("provided_type_ok.kt")
    public void testProvided_type_ok() {
      runTest("koin-compiler-plugin/testData/box/safety/provided_type_ok.kt");
    }

    @Test
    @TestMetadata("qualifier_match.kt")
    public void testQualifier_match() {
      runTest("koin-compiler-plugin/testData/box/safety/qualifier_match.kt");
    }

    @Test
    @TestMetadata("scoped_visibility.kt")
    public void testScoped_visibility() {
      runTest("koin-compiler-plugin/testData/box/safety/scoped_visibility.kt");
    }

    @Test
    @TestMetadata("startkoin_full_graph.kt")
    public void testStartkoin_full_graph() {
      runTest("koin-compiler-plugin/testData/box/safety/startkoin_full_graph.kt");
    }

    @Test
    @TestMetadata("toplevel_function_ok.kt")
    public void testToplevel_function_ok() {
      runTest("koin-compiler-plugin/testData/box/safety/toplevel_function_ok.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/scopes")
  @TestDataPath("$PROJECT_ROOT")
  public class Scopes {
    @Test
    public void testAllFilesPresentInScopes() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/scopes"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("scope_class.kt")
    public void testScope_class() {
      runTest("koin-compiler-plugin/testData/box/scopes/scope_class.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/startkoin")
  @TestDataPath("$PROJECT_ROOT")
  public class Startkoin {
    @Test
    public void testAllFilesPresentInStartkoin() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/startkoin"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("configuration_discovery.kt")
    public void testConfiguration_discovery() {
      runTest("koin-compiler-plugin/testData/box/startkoin/configuration_discovery.kt");
    }

    @Test
    @TestMetadata("koin_application.kt")
    public void testKoin_application() {
      runTest("koin-compiler-plugin/testData/box/startkoin/koin_application.kt");
    }

    @Test
    @TestMetadata("multiple_modules.kt")
    public void testMultiple_modules() {
      runTest("koin-compiler-plugin/testData/box/startkoin/multiple_modules.kt");
    }

    @Test
    @TestMetadata("startkoin_basic.kt")
    public void testStartkoin_basic() {
      runTest("koin-compiler-plugin/testData/box/startkoin/startkoin_basic.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/toplevel")
  @TestDataPath("$PROJECT_ROOT")
  public class Toplevel {
    @Test
    public void testAllFilesPresentInToplevel() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/toplevel"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("singleton_function.kt")
    public void testSingleton_function() {
      runTest("koin-compiler-plugin/testData/box/toplevel/singleton_function.kt");
    }
  }
}
