

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("koin-compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("configuration_label_mismatch.kt")
  public void testConfiguration_label_mismatch() {
    runTest("koin-compiler-plugin/testData/diagnostics/configuration_label_mismatch.kt");
  }

  @Test
  @TestMetadata("dsl_module_not_loaded.kt")
  public void testDsl_module_not_loaded() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_module_not_loaded.kt");
  }

  @Test
  @TestMetadata("lazy_missing.kt")
  public void testLazy_missing() {
    runTest("koin-compiler-plugin/testData/diagnostics/lazy_missing.kt");
  }

  @Test
  @TestMetadata("missing_dependency.kt")
  public void testMissing_dependency() {
    runTest("koin-compiler-plugin/testData/diagnostics/missing_dependency.kt");
  }

  @Test
  @TestMetadata("provided_missing.kt")
  public void testProvided_missing() {
    runTest("koin-compiler-plugin/testData/diagnostics/provided_missing.kt");
  }

  @Test
  @TestMetadata("qualifier_mismatch.kt")
  public void testQualifier_mismatch() {
    runTest("koin-compiler-plugin/testData/diagnostics/qualifier_mismatch.kt");
  }

  @Test
  @TestMetadata("scoped_cross_scope.kt")
  public void testScoped_cross_scope() {
    runTest("koin-compiler-plugin/testData/diagnostics/scoped_cross_scope.kt");
  }

  @Test
  @TestMetadata("startkoin_missing.kt")
  public void testStartkoin_missing() {
    runTest("koin-compiler-plugin/testData/diagnostics/startkoin_missing.kt");
  }
}
