package org.koin.compiler.plugin.ir

import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.koin.compiler.plugin.KoinPluginLogger

class KoinIrExtension : IrGenerationExtension {
    override fun generate(moduleFragment: IrModuleFragment, pluginContext: IrPluginContext) {
        KoinPluginLogger.debug { "IR Phase starting for module: ${moduleFragment.name}" }

        // Phase 0: Generate bodies for FIR-generated hint functions and registry function
        // These are generated by KoinModuleFirGenerator in FIR phase
        KoinPluginLogger.debug { "Phase 0: Generating hint function bodies" }
        val hintBodyGenerator = KoinHintTransformer(pluginContext)
        moduleFragment.transform(hintBodyGenerator, null)

        // Shared qualifier extractor and optional safety validator
        val qualifierExtractor = QualifierExtractor(pluginContext)
        val safetyValidator = if (KoinPluginLogger.safetyChecksEnabled) {
            KoinPluginLogger.debug { "Compile safety: ENABLED (skipDefaultValues=${KoinPluginLogger.skipDefaultValuesEnabled})" }
            CompileSafetyValidator(qualifierExtractor)
        } else {
            KoinPluginLogger.debug { "Compile safety: DISABLED" }
            null
        }

        // Phase 1: Process @Module/@ComponentScan/@Singleton/@Factory annotations
        // Generates: fun MyModule.module() = module { single<A>(); factory<B>() }
        KoinPluginLogger.debug { "Phase 1: Processing annotations" }
        val annotationProcessor = KoinAnnotationProcessor(pluginContext, qualifierExtractor, safetyValidator)
        annotationProcessor.collectAnnotations(moduleFragment)
        annotationProcessor.generateModuleExtensions(moduleFragment)

        // Phase 2: Transform single<T>() -> single(T::class, null) { T(get()) }
        KoinPluginLogger.debug { "Phase 2: Transforming DSL calls" }
        val koinTransformer = KoinDSLTransformer(pluginContext)
        moduleFragment.transform(koinTransformer, null)

        // Phase 3: Transform startKoin<T> { } to inject modules()
        // Transforms: startKoin<MyApp> { printLogger() }
        // Into: startKoin { printLogger(); modules(listOf(Module1().module, ...)) }
        KoinPluginLogger.debug { "Phase 3: Transforming startKoin calls" }
        val startKoinTransformer = KoinStartTransformer(pluginContext, moduleFragment, annotationProcessor, safetyValidator)
        moduleFragment.transform(startKoinTransformer, null)

        // Phase 4: Transform @Monitor annotated functions
        // Wraps function bodies with Kotzilla trace calls for performance monitoring
        KoinPluginLogger.debug { "Phase 4: Processing @Monitor annotations" }
        val monitorTransformer = KoinMonitorTransformer(pluginContext)
        moduleFragment.transform(monitorTransformer, null)

        KoinPluginLogger.debug { "IR Phase completed" }
    }
}
