package org.koin.compiler.plugin.ir

import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.incremental.components.ExpectActualTracker
import org.jetbrains.kotlin.incremental.components.LookupTracker
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.koin.compiler.plugin.KoinPluginLogger

class KoinIrExtension(
    private val lookupTracker: LookupTracker?,
    private val expectActualTracker: ExpectActualTracker
) : IrGenerationExtension {
    override fun generate(moduleFragment: IrModuleFragment, pluginContext: IrPluginContext) {
        KoinPluginLogger.debug { "IR Phase starting for module: ${moduleFragment.name}" }

        // Phase 0: Generate bodies for FIR-generated hint functions and registry function
        // These are generated by KoinModuleFirGenerator in FIR phase
        KoinPluginLogger.debug { "Phase 0: Generating hint function bodies" }
        val hintBodyGenerator = KoinHintTransformer(pluginContext)
        moduleFragment.transform(hintBodyGenerator, null)

        // Shared qualifier extractor and optional safety validator
        val qualifierExtractor = QualifierExtractor(pluginContext)
        val safetyValidator = if (KoinPluginLogger.compileSafetyEnabled) {
            KoinPluginLogger.debug { "Compile safety: ENABLED (skipDefaultValues=${KoinPluginLogger.skipDefaultValuesEnabled})" }
            CompileSafetyValidator(qualifierExtractor)
        } else {
            KoinPluginLogger.debug { "Compile safety: DISABLED" }
            null
        }

        // Phase 1: Process @Module/@ComponentScan/@Singleton/@Factory annotations
        // Generates: fun MyModule.module() = module { single<A>(); factory<B>() }
        KoinPluginLogger.debug { "Phase 1: Processing annotations" }
        val annotationProcessor = KoinAnnotationProcessor(pluginContext, qualifierExtractor, safetyValidator, lookupTracker, expectActualTracker)
        annotationProcessor.collectAnnotations(moduleFragment)
        annotationProcessor.generateModuleExtensions(moduleFragment)

        // Phase 2: Transform single<T>() -> single(T::class, null) { T(get()) }
        // Also collects DSL definitions and pending call-site validations
        KoinPluginLogger.debug { "Phase 2: Transforming DSL calls" }
        val koinTransformer = KoinDSLTransformer(pluginContext, lookupTracker)
        moduleFragment.transform(koinTransformer, null)
        val dslDefinitions = koinTransformer.dslDefinitions
        val pendingCallSites = koinTransformer.collectedCallSites
        KoinPluginLogger.debug { "Phase 2: Collected ${dslDefinitions.size} DSL definitions, ${pendingCallSites.size} pending call sites" }

        // Instantiate extracted helper classes
        val dslHintGenerator = DslHintGenerator(pluginContext)
        val callSiteValidator = CallSiteValidator(pluginContext)

        // Phase 2.5: Generate DSL definition hints for cross-module discovery
        // Each DSL definition (single<T>, factory<T>, etc.) generates a hint function
        // so downstream modules can discover these definitions via referenceFunctions()
        if (dslDefinitions.isNotEmpty() && KoinPluginLogger.compileSafetyEnabled) {
            KoinPluginLogger.debug { "Phase 2.5: Generating ${dslDefinitions.size} DSL definition hints" }
            dslHintGenerator.generateDslDefinitionHints(moduleFragment, dslDefinitions)
        }

        // Phase 3: Transform startKoin<T> { } to inject modules()
        // Transforms: startKoin<MyApp> { printLogger() }
        // Into: startKoin { printLogger(); modules(listOf(Module1().module, ...)) }
        // A3 full-graph validation includes DSL definitions as providers + consumers
        KoinPluginLogger.debug { "Phase 3: Transforming startKoin calls" }
        val startKoinTransformer = KoinStartTransformer(pluginContext, moduleFragment, annotationProcessor, safetyValidator, lookupTracker, expectActualTracker, dslDefinitions)
        moduleFragment.transform(startKoinTransformer, null)

        // Phase 3.1: DSL-only A3 validation (when startKoin { } is present but no startKoin<T>() / @KoinApplication)
        // Validates constructor parameters of local DSL definitions against all known definitions.
        // This catches missing definitions like commenting out single<Repository>() that a ViewModel needs.
        // Only runs in the entry-point module (the one that calls startKoin { }) to avoid false positives
        // in leaf modules that don't have the full graph visible.
        if (safetyValidator != null && dslDefinitions.isNotEmpty()
            && safetyValidator.assembledGraphTypes.isEmpty()
            && startKoinTransformer.hasKoinEntryPoint) {
            KoinPluginLogger.debug { "Phase 3.1: DSL-only A3 validation (${dslDefinitions.size} local DSL definitions)" }
            callSiteValidator.validateDslDefinitionGraph(
                dslDefinitions, annotationProcessor, safetyValidator, dslHintGenerator,
                koinTransformer.startKoinModules, koinTransformer.moduleIncludes
            )
        }

        // Phase 3.5: Validate pending call sites (simple loop, no tree walk)
        // Checks collected call sites against the assembled graph + DSL definitions.
        // Unresolved call sites (when no full graph) generate call-site hints for deferred validation.
        if (safetyValidator != null && pendingCallSites.isNotEmpty()) {
            KoinPluginLogger.debug { "Phase 3.5: Validating ${pendingCallSites.size} call-site resolutions (graph types: ${safetyValidator.assembledGraphTypes.size})" }
            callSiteValidator.validatePendingCallSites(moduleFragment, pendingCallSites, safetyValidator.assembledGraphTypes, dslDefinitions, annotationProcessor, dslHintGenerator)
        }

        // Phase 3.6: Validate call-site hints from dependency modules against known definitions
        // Call-site hints are generated by feature modules that can't resolve call sites locally.
        // The app module (which sees all definitions via @KoinApplication) validates them here.
        // Only runs when a full graph has been assembled — without @KoinApplication, the compilation
        // unit doesn't have visibility into all modules and would produce false positives.
        if (safetyValidator != null && KoinPluginLogger.compileSafetyEnabled
            && safetyValidator.assembledGraphTypes.isNotEmpty()) {
            callSiteValidator.validateCallSiteHintsFromDependencies(safetyValidator.assembledGraphTypes, dslDefinitions, annotationProcessor, dslHintGenerator)
        }

        // Phase 4: Transform @Monitor annotated functions
        // Wraps function bodies with Kotzilla trace calls for performance monitoring
        KoinPluginLogger.debug { "Phase 4: Processing @Monitor annotations" }
        val monitorTransformer = KoinMonitorTransformer(pluginContext)
        moduleFragment.transform(monitorTransformer, null)
        monitorTransformer.logSummary()

        KoinPluginLogger.debug { "IR Phase completed" }
    }
}
